### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/acmi-wikidata-bot#7]
Morning @paulduchesne,

Checking the logs today I'm seeing ([sentry](https://acmi.sentry.io/issues/4654199094/?project=4505356243042304&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0)):

```bash
Traceback (most recent call last):
  File "/home/epd/Code/acmi-wikidata-bot/acmi_bot.py", line 103, in <module>
    wd_item = wbi.item.get(
  File "/home/epd/Code/acmi-wikidata-bot/venv/lib/python3.10/site-packages/wikibaseintegrator/entities/item.py", line 108, in get
    return ItemEntity(api=self.api).from_json(json_data=json_data['entities'][entity_id])
  File "/home/epd/Code/acmi-wikidata-bot/venv/lib/python3.10/site-packages/wikibaseintegrator/entities/item.py", line 124, in from_json
    super().from_json(json_data=json_data)
  File "/home/epd/Code/acmi-wikidata-bot/venv/lib/python3.10/site-packages/wikibaseintegrator/entities/baseentity.py", line 145, in from_json
    raise MissingEntityException('The MW API returned that the entity was missing.')
wikibaseintegrator.wbi_exceptions.MissingEntityException: The MW API returned that the entity was missing.
```

So maybe we should print/capture the Wikidata ID we're trying, or do a try/except so we don't crash out for missing entities?

**Comment by paulduchesne** [comment]
Yes, grabbing that entity_id would be very handy to understand what the issue is. My suspicion is that there is a stored wikidata id acmi-side which no longer exists.
